name: parkingpage

services:
  parkingpage:
    image: ghcr.io/ivancarlosti/parkingpage:latest
    env_file: .env
    container_name: parkingpage
    restart: unless-stopped
# BEGIN remove comment for testing using custom PHP
#    volumes:
#      - ./www:/var/www/html
# END remove comment for testing using custom PHP
    entrypoint: ["/startup.sh"]
    ports:
      - "5666:80"  # expose port 5666 to host
    extra_hosts:
      - host.docker.internal:host-gateway
